name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-program-and-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Set executable permissions
      run: |
        chmod 777 -R /home/runner/work/MWOProject/MWOProject

    # Start API
    - name: Start API and WEB App
      run: nohup dotnet /home/runner/work/MWOProject/MWOProject/VehicleDealershipApp/bin/Release/net7.0/VehicleDealershipApp.Client.dll &

    # Wait for services to start (you may need to adjust the sleep duration)
    - name: Wait for services
      run: sleep 10

    # Run Selenium tests
    - name: Run Selenium tests
      run: dotnet test --verbosity normal --urls 'https://localhost:7255/VehicleApi'

    # Additional steps (e.g., stopping services, cleaning up, etc.) if needed
